apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo2
  namespace: odoo
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.odoo: glob:live.v1.*
  labels:
    app: odoo2

spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo2
  template:
    metadata:
      labels:
        app: odoo2
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - image: itsscmp/sanie:beta.v1.3
          name: odoo
          env:
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: dbconfig
                key: host
          - name: DATABASE
            valueFrom:
              configMapKeyRef:
                name: dbconfig
                key: database  
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: dbconfig
                key: port
          - name: USER
            valueFrom:
              secretKeyRef:
                name: dbsecret
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbsecret
                key: password  
          ports:
            - containerPort: 8069
              name: odoo-port
          readinessProbe:
            httpGet:
              path: /
              port: odoo-port
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1